name: skillex
description: Application de formation vidéo avec authentification Firebase
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.1.6
  firebase_storage: ^12.1.1
  image_picker: ^1.1.1
  
  # YouTube Player
  youtube_player_flutter: ^9.1.1
  
  # WebView
  flutter_inappwebview: ^6.0.0
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  animations: ^2.0.8
  lottie: ^3.3.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utilities
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.20.2
  url_launcher: ^6.2.1
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Icons & Fonts
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # New dependencies
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  dart_code_metrics: 4.19.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/google_logo.png
    - assets/animations/
    - assets/icons/
    - assets/fonts/
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  # background_color_android: "#ffffff" # Optionnel: définissez une couleur de fond
  # foreground_image_android: "assets/images/logo.png" # Optionnel: si vous avez une image de premier plan différente pour Android
