// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import '../config/api_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ApiConfig.firebaseApiKey,
    appId: ApiConfig.firebaseAppId,
    messagingSenderId: ApiConfig.firebaseMessagingSenderId,
    projectId: ApiConfig.firebaseProjectId,
    authDomain: ApiConfig.firebaseAuthDomain,
    storageBucket: ApiConfig.firebaseStorageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ApiConfig.firebaseApiKey,
    appId: ApiConfig.firebaseAppId,
    messagingSenderId: ApiConfig.firebaseMessagingSenderId,
    projectId: ApiConfig.firebaseProjectId,
    storageBucket: ApiConfig.firebaseStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiConfig.firebaseApiKey,
    appId: ApiConfig.firebaseAppId,
    messagingSenderId: ApiConfig.firebaseMessagingSenderId,
    projectId: ApiConfig.firebaseProjectId,
    storageBucket: ApiConfig.firebaseStorageBucket,
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.skillex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ApiConfig.firebaseApiKey,
    appId: ApiConfig.firebaseAppId,
    messagingSenderId: ApiConfig.firebaseMessagingSenderId,
    projectId: ApiConfig.firebaseProjectId,
    storageBucket: ApiConfig.firebaseStorageBucket,
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.skillex',
  );

}