// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7zMLkVkU9uRbCpOPsVkt365XCbxPvJis',
    appId: '1:320421822385:web:5b37dac32d59d6bc86c790',
    messagingSenderId: '320421822385',
    projectId: 'skillex-f4084',
    authDomain: 'skillex-f4084.firebaseapp.com',
    storageBucket: 'skillex-f4084.firebasestorage.app',
    measurementId: 'G-Z82Y0WJKS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0vfP9K1ZComswh6fkIFqi9JqnPy2wic',
    appId: '1:320421822385:android:7b9da9dd6842230986c790',
    messagingSenderId: '320421822385',
    projectId: 'skillex-f4084',
    storageBucket: 'skillex-f4084.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpyEhBqX64kk3WoZIDVd3A5bFqeTutnhw',
    appId: '1:320421822385:ios:9a3698a28acfb61f86c790',
    messagingSenderId: '320421822385',
    projectId: 'skillex-f4084',
    storageBucket: 'skillex-f4084.firebasestorage.app',
    androidClientId: '320421822385-j5d2h8giqes9m2cpnu73gohsj11jpm5r.apps.googleusercontent.com',
    iosClientId: '320421822385-649kvdqqsp4agt28ft9cg7v336fij4qc.apps.googleusercontent.com',
    iosBundleId: 'cm.mediasystem.skillex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpyEhBqX64kk3WoZIDVd3A5bFqeTutnhw',
    appId: '1:320421822385:ios:9a3698a28acfb61f86c790',
    messagingSenderId: '320421822385',
    projectId: 'skillex-f4084',
    storageBucket: 'skillex-f4084.firebasestorage.app',
    androidClientId: '320421822385-j5d2h8giqes9m2cpnu73gohsj11jpm5r.apps.googleusercontent.com',
    iosClientId: '320421822385-649kvdqqsp4agt28ft9cg7v336fij4qc.apps.googleusercontent.com',
    iosBundleId: 'cm.mediasystem.skillex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7zMLkVkU9uRbCpOPsVkt365XCbxPvJis',
    appId: '1:320421822385:web:06f92dc37ac3641f86c790',
    messagingSenderId: '320421822385',
    projectId: 'skillex-f4084',
    authDomain: 'skillex-f4084.firebaseapp.com',
    storageBucket: 'skillex-f4084.firebasestorage.app',
    measurementId: 'G-PSDS5P0DLS',
  );

}